In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
from io import StringIO
from datetime import timedelta

#prevents warnings from being printed
import warnings
warnings.filterwarnings('ignore')

In [ ]:
sd = pd.read_csv('sd_requests.csv')
sd = sd.convert_dtypes()
sd.head()

        id  ...                                               msgs
0  15-1810  ...  title,item,time
"Request Closed
Public",02. Re...
1  15-1811  ...  title,item,time
"Request Published
Public",,"D...
2  15-1812  ...  title,item,time
"Request Closed
Public",Still ...
3  15-1813  ...  title,item,time
"Request Closed
Public",02. Re...
4  15-1814  ...  title,item,time
"Request Closed
Public",02. Re...

[5 rows x 8 columns]

In [ ]:
sd.shape

(28848, 8)

In [ ]:
sd = sd.rename(columns = {'date': 'request date'})
sd = sd.fillna('')

sd['city'] = 'San Diego'
sd['state'] = 'CA'

In [ ]:
csv_to_df = lambda csv: pd.read_csv(StringIO(csv)) if csv else None
sd['docs_csv'] = sd['docs'].map(csv_to_df)
sd['msgs_csv'] = sd['msgs'].map(csv_to_df)

sd['docs_csv'] = sd['docs_csv'].map(lambda df: df.convert_dtypes().fillna('') if df is not None else None)
sd['msgs_csv'] = sd['msgs_csv'].map(lambda df: df.convert_dtypes().fillna('') if df is not None else None)

In [ ]:
sd['num docs'] = sd['docs_csv'].map(lambda df: len(df) if df is not None else 0)
sd.head()

        id  status  ...                                           msgs_csv num docs
0  15-1810  CLOSED  ...                            title  ...          ...        2
1  15-1811  CLOSED  ...                            title  ...          ...        0
2  15-1812  CLOSED  ...                            title  ...          ...        1
3  15-1813  CLOSED  ...                            title  ...          ...        0
4  15-1814  CLOSED  ...                             title  ...         ...        2

[5 rows x 13 columns]

In [ ]:
sd['request d'] = sd['request date'].map(lambda x: x[:len(x) - 8]).map(lambda x: x.replace(',', '')).map(add0)

In [ ]:
sd.head()

        id  status  ...                                           msgs_csv num docs
0  15-1810  CLOSED  ...                            title  ...          ...        2
1  15-1811  CLOSED  ...                            title  ...          ...        0
2  15-1812  CLOSED  ...                            title  ...          ...        1
3  15-1813  CLOSED  ...                            title  ...          ...        0
4  15-1814  CLOSED  ...                             title  ...         ...        2

[5 rows x 13 columns]

In [ ]:
def add0(txt):  
  lst = txt.split(' ')
  x = txt.find(' ')
  if len(lst[1]) ==1:
    return txt[:x+1]+'0'+txt[x+1:]
  else:
    return txt
sd['request d'] = sd['request d'].map(add0).map(lambda x: x.replace(' ', ''))

In [ ]:
sd.head()

        id  status  ... num docs       request d
0  15-1810  CLOSED  ...        2  December072015
1  15-1811  CLOSED  ...        0  December072015
2  15-1812  CLOSED  ...        1  December072015
3  15-1813  CLOSED  ...        0  December072015
4  15-1814  CLOSED  ...        2  December072015

[5 rows x 14 columns]